name: 8.6 Documentation request
description: Request docs for 8.6
title: "[REQUEST]: "
labels: ["8.6-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what needs to be documented.
      placeholder: I need...
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: Relevant information
      description: Please link to any relevant information, including issues, PRs, demos, conversations, etc.
      placeholder: How can the docs team learn more about this feature?
    validations:
      required: true
  - type: dropdown
    id: collaboration
    attributes:
      label: Collaboration
      description: Choose the expected collaboration model
      options:
        - 1.0.2 (Default)
        - The **docs** team will proide the initial content.
        - The **product** team will provide the initial content.
        - TBD. The docs and product team will work together to determine the best path forward.
        - Other (please describe above).
    validations:
      required: true
  - type: textarea
    id: contact
    attributes:
      label: Contact person.
      description: Please assign at least one contact person using the GitHub `@` mention. Add as many stakeholders as you'd like.
  - type: input
    id: contacts
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
    validations:
      required: false
