name: 8.6 Documentation request
description: Request a documnetation update for Elastic Stack version 8.6
title: "[REQUEST]: "
labels: ["8.6-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request! This form will create an issue that the obs-docs team will triage and prioritize. Filling out this form does not guarantee that your issue will be prioritized for the selected iteration.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what needs to be documented.
      placeholder: I need...
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: Resources
      description: Please link to as many related resources as possible. Think about issues, PRs, demos, Slack threads, etc.
      placeholder: How can the docs team learn more about this feature?
    validations:
      required: true
  - type: checkboxes
    id: collaboration
    attributes:
      label: Collaboration
      description: Choose the expected collaboration model
      options:
        label: 1.0.2 (Default)
        label: The **docs** team will proide the initial content.
        label: The **product** team will provide the initial content.
        label: TBD. The docs and product team will work together to determine the best path forward.
        label: Other (please describe above).
    validations:
      required: true
  - type: textarea
    id: contact
    attributes:
      label: Contact person.
      description: Please assign at least one contact person using the GitHub `@` mention. Add as many stakeholders as you'd like.
  - type: input
    id: contacts
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
    validations:
      required: false
